FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# api-test

Product is a simple API allowing consumers to view our products.

## Questions Collection [/products/{id}]

### List All products [GET]
+ Parameters
    + id (number, optional)

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "p1",
                "type": "event"
            },
            {
                "id": 2,
                "name": "p2",
                "type": "ACTIVITY"
            }
        ]

### Create a New Product [POST]

You may create your own product using this action. It takes a JSON
object containing a product with its atributes.

+ Request (application/json)

        {   "name": "p3",
            "type": "ACTIVITY"
        }

+ Response 201 (application/json)

    + Headers

            Location: /products/3

    + Body

            {
                 [
                    {
                        "id" = 3,
                        "name": "p3",
                        "type": "ACTIVITY"
                    }
                ]
            }
            
            
### Update a product [PUT]

You may update a product using this action. It takes a JSON
object containing a product with its atributes.


+ Request (application/json)

        {   
            "id" = 3,
            "name": "producto3",
            "type": "EVENT"
        }

+ Response 200 (application/json)

    + Headers

            Location: /products/3

    + Body

            {
                 [
                    {
                        "id" = 3,
                        "name": "producto3",
                        "type": "EVENT"
                    }
                ]
            }